typography_spectrum: 0.97002
color:
  brandColors:
    - '#1a2b57'
    - '#33598b'
    - '#1a3b6a'
    - '#324976'
    - '#135084'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.59476
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f6ffda55-4b06-4f99-aa64-1bda8a7374a9.png
name: 'Isadore Private Wealth, LLC'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Tailored Services
    id: 95860490-8b9f-40a0-841b-1338b957cb76
    type: content
  - name: 'Portfolio Design '
    id: d9ed1e82-aee0-4793-bfe2-1c942fe424aa
    type: content
  - name: Meet Neil
    id: ef77c211-dea1-4885-bba8-33efcb3f85b1
    type: content
  - name: 'Contact '
    id: 3121dbbf-b904-4757-9249-912fefe04bca
    type: content
favicon: null
title: IPW
description: The Disciplined Pursuit of Global Investment Opportunities
purpose: []
