name: IPW
favicon: null
layout_spectrum: 0.8946825773455203
typography_spectrum: 0.5057060460094362
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7507626384031028
  lightness: 0.553362313657999
  saturation: 0.7563411667943001
  rhythmicContrast: 0.6161869859788567
purpose: []
