typography_spectrum: 0.97002
color:
  brandColors:
    - '#1a2b57'
    - '#33598b'
    - '#1a3b6a'
    - '#324976'
    - '#135084'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.59476
analytics:
  google: null
  facebook: null
  twitter: null
name: IPW
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Tailored Services
    id: 95860490-8b9f-40a0-841b-1338b957cb76
    type: content
favicon: null
title: 'Isadore Private Wealth, LLC'
description: The Disciplined Pursuit of Global Investment Opportunities
purpose: []
