typography_spectrum: 0.97002
color:
  brandColors:
    - '#1a2b57'
    - '#33598b'
    - '#1a3b6a'
    - '#324976'
    - '#135084'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.59476
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5869b5f9-5e82-42b1-9c3e-1373cc7ae514.png
name: IPW
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Tailored Services
    id: 95860490-8b9f-40a0-841b-1338b957cb76
    type: content
  - name: Planning & Strategy
    id: bee9bea2-c91d-41b8-ba10-f9af42ff2e93
    type: content
  - name: 'Portfolio Design '
    id: d9ed1e82-aee0-4793-bfe2-1c942fe424aa
    type: content
  - name: Meet Neil
    id: ef77c211-dea1-4885-bba8-33efcb3f85b1
    type: content
favicon: null
title: 'Isadore Private Wealth, LLC'
description: The Disciplined Pursuit of Global Investment Opportunities
purpose: []
